### ISSUE TITLE
For buttons, use backgroundTint instead of background

### ISSUE THREAD

**Issue by LavishSwarnkar** [MohitSinghFlutter/ScoreKeeper#1]
Change [here](https://github.com/MohitSinghFlutter/ScoreKeeper/blob/01551c691d30b6bfca7a9e0f89ca29d569256fe3/app/src/main/res/layout/activity_main.xml#L46) and everywhere else.

**Comment by MohitSingh2002** [comment]
Changed background with backgroundTint
